# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software Musings
email: juliuskrah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development blog that uses JavaEE and other related web technologies
  with a strong emphasis on Spring, Thymeleaf, Websockets and Microservices
baseurl: "" # the subpath of your site, e.g. /blog
github:
  url: https://github.com
permalink: /:categories/:year/:month/:day/:title/
url: "http://juliuskrah.com" # the base hostname & protocol for your site
author: juliuskrah
twitter:
  username: juliuskrah
disqus:
  shortname: juliuskrah
google_analytics: UA-86031412-1
github_username:  juliuskrah
stackoverflow_link: users/6157880/julius-krah
repository: juliuskrah/juliuskrah.github.io
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Default is https://github.com
jekyll-mentions:
  base_url: https://twitter.com

# Build settings
markdown: kramdown
# kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  # input: GFM
  # Disable auto-generated ID's for headings
  # auto_ids: false
theme: minima
exclude:
  - README.md
  - .gitignore
