# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julius' Blog
email: juliuskrah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development blog that uses Java and other related web technologies
  with a strong emphasis on spring, thymeleaf, websockets and microservices
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://juliuskrah.github.io" # the base hostname & protocol for your site
twitter_username: abeiku85
github_username:  juliuskrah

# Build settings
markdown: kramdown
